---
deployment:
      tasks:
        - export DEPLOYPATH=/home4/africda3/public_html/itwebsite  # Add /<app_folder> if required
        - /bin cp -r * $DEPLOYPATH                           #copy all from root